package programmateurs.models;

import java.util.ArrayList;
import java.util.List;

import programmateurs.beans.Category;
import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;

/**
 * This class manages access to categories data in the db.
 * 
 * @author vancan1ty
 * 
 */
public final class CategoriesDAO {

    /**
     * hide the constructor, appease the checkstyle gods!
     */
    private CategoriesDAO() {

    }

    /**
     * this is the sql to build the categories table.
     */
    public static final String CREATE_CATEGORIES_TABLE = "CREATE TABLE Categories"
            + " (categoryID INTEGER PRIMARY KEY AUTOINCREMENT, "
            + " userID INTEGER,"
            + " category_name TEXT NOT NULL,"
            + " FOREIGN KEY(userID) REFERENCES Users(userID)" + ");";

    // NO LONGER NEEDED BECAUSE ONLY ONE CATEGORY PER TRANSACTION
    /*
     * public static final String CREATE_TRANSACTIONS_CATEGORIES_TABLE =
     * "CREATE TABLE Transactions_Categories" +
     * " (transactions_categoriesID INTEGER PRIMARY KEY AUTOINCREMENT, " +
     * " transactionID INTEGER NOT NULL, " + " categoryID INTEGER NOT NULL, " +
     * " FOREIGN KEY(transactionID) REFERENCES Transactions(transactionID), " +
     * " FOREIGN KEY(categoryID) REFERENCES Categories(categoryID)" + ");";
     */

    /**
     * converts a db cursor generated by one of the associated methods to a
     * Category object.
     * 
     * @param cursor
     *            a db cursor
     * @return a category object.
     */
    private static Category cursorToCategory(final Cursor cursor) {
        long categoryID = cursor.getInt(0);
        long userID = cursor.getInt(1);
        String categoryName = cursor.getString(2);

        return new Category(categoryID, userID, categoryName);
    }

    /**
     * returns a list of all categories owned by a given user.
     * 
     * @param db
     *            a db connection to perform the query on.
     * @param userID
     *            the id of the user to get categories for.
     * @return list of categories owned by user
     */
    public static Category[] getCategoriesForUser(final SQLiteDatabase db,
            final long userID) {

        Cursor c = db.rawQuery("SELECT * FROM categories WHERE userid = ?;",
                new String[] { Long.toString(userID) });
        List<Category> outL = new ArrayList<Category>();

        c.moveToFirst();
        while (!c.isAfterLast()) {
            Category cat = cursorToCategory(c);
            outL.add(cat);
            c.moveToNext();
        }
        // make sure to close the cursor
        c.close();
        return outL.toArray(new Category[0]);
    }

    /**
     * returns all the categories associated with a given transaction.
     * 
     * @param db
     *            a db connection to query.
     * @param transactionID
     *            the id of the transaction in the db.
     * @return an array of categories.
     */
    public static Category[] getCategoriesForTransaction(
            final SQLiteDatabase db, final long transactionID) {

        Cursor c = db.rawQuery(
                "SELECT C.categoryID, C.userID, C.category_name "
                        + "FROM Transactions as T "
                        + "JOIN Transactions_Categories as TC "
                        + "JOIN Categories as C " + "WHERE T.transactionID = ?"
                        + "AND TC.transactionID = T.transactionID"
                        + "AND TC.categoryID = C.categoryID;",
                new String[] { Long.toString(transactionID) });
        List<Category> outL = new ArrayList<Category>();

        c.moveToFirst();
        while (!c.isAfterLast()) {
            Category cat = cursorToCategory(c);
            outL.add(cat);
            c.moveToNext();
        }
        // make sure to close the cursor
        c.close();
        return outL.toArray(new Category[0]);
    }

    /**
     * adds a category with the associated information to the DB, returns an
     * object representation of it.
     * 
     * @param db
     *            db connection to query
     * @param userID
     *            the user to add the category for
     * @param categoryName
     *            the actual name of the category.
     * @return a copy of the category object that was just put in the db.
     */
    public static Category addCategoryForDB(final SQLiteDatabase db,
            final long userID, final String categoryName) {
        ContentValues toInsert = new ContentValues();
        toInsert.put("userID", userID);
        toInsert.put("category_name", categoryName);
        long categoryID = db.insert("categories", null, toInsert);
        Category cat = new Category(categoryID, userID, categoryName);
        return cat;
    }
}
